name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - production

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_DEPLOYER_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate Docker
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REPO_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        working-directory: ./
        run: docker build . --file Dockerfile --tag ${{ secrets.GCP_REPO_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bnmo-projects-repo/bnmo-library-be

      - name: Push image
        run: docker push ${{ secrets.GCP_REPO_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bnmo-projects-repo/bnmo-library-be

      - name: Deploy image to Google Cloud Run
        run: |
          gcloud run deploy bnmo-library-be \
            --image ${{ secrets.GCP_REPO_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/bnmo-projects-repo/bnmo-library-be:latest \
            --platform managed \
            --region ${{ secrets.GCP_CLOUD_RUN_REGION }} \
            --allow-unauthenticated \
            --set-env-vars RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} \
            --set-env-vars JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }} \
            --set-env-vars JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
            --set-env-vars PRODUCTION_DATABASE_PASSWORD=${{ secrets.PRODUCTION_DATABASE_PASSWORD }} \
            --port 3000 \
            --min-instances 1 \
            --max-instances 4
